#!/usr/bin/env bash

id=$(ps -ef | grep '[w]aybar -c' | awk '{print $2}')

if true; then
	# pkill -x waybar
	killall dunst
	rm -f $XDG_RUNTIME_DIR/wob.sock
	systemctl --user stop wob
	systemctl --user stop wob.socket && systemctl --user start wob.socket
	if $(kill -SIGUSR2 $id); then
		notify-send --urgency=low --transient "Bar refreshed!" "Alt+Shift+R to refresh!" -r 9000
		notify-send --urgency=normal --transient "Bar refreshed!" "Alt+Shift+R to refresh!" -r 9001
		notify-send --urgency=critical --transient "Bar refreshed!" "Alt+Shift+R to refresh!" -r 9002 -t 4000
		waybar \
			-c ~/.config/waybar/base/config.jsonc \
			-s ~/.config/waybar/base/style.css & disown
		waybar \
			-c ~/.config/waybar/utilities/config.jsonc \
			-s ~/.config/waybar/utilities/style.css & disown
		waybar \
			-c ~/.config/waybar/power/config.jsonc \
			-s ~/.config/waybar/power/style.css & disown
		waybar \
			-c ~/.config/waybar/calendar/config.jsonc \
			-s ~/.config/waybar/calendar/style.css & disown
	fi
fi
