#!/usr/bin/env bash

if true; then
	pkill -x waybar
    killall dunst
	rm -f $XDG_RUNTIME_DIR/wob.sock
	systemctl --user stop wob
	systemctl --user stop wob.socket && systemctl --user start wob.socket
    notify-send --urgency=low --transient "Bar refreshed!" "Alt+Shift+R to refresh!" -r 9000
    notify-send --urgency=normal --transient "Bar refreshed!" "Alt+Shift+R to refresh!" -r 9001
    notify-send --urgency=critical --transient "Bar refreshed!" "Alt+Shift+R to refresh!" -r 9002 -t 4000
	waybar \
		-c ~/.config/waybar/base/config.jsonc \
		-s ~/.config/waybar/base/style.css
fi
